# Generated by Django 5.1.1 on 2024-09-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_users_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
