# Generated by Django 5.1.1 on 2024-09-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_remove_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
