# Generated by Django 5.1.1 on 2024-10-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('rank', models.CharField(max_length=255)),
                ('work', models.CharField(max_length=255)),
                ('work_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
