# Generated by Django 5.1.1 on 2024-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_usersform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
