# Generated by Django 5.1.1 on 2024-10-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0007_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
