# Generated by Django 5.1.1 on 2024-10-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0008_uploadedfile_text_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='text',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
